import type { ApiSpec, EndpointSpec, FieldSpec } from "./types.js";

export function generateTsSdk(api: ApiSpec): string {
  const className = toClassName(api.title) + "Client";
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * ${api.title} TypeScript SDK`);
  lines.push(` * Generated by openspec-generator. Do not edit manually.`);
  lines.push(` */`);
  lines.push("");
  lines.push(`export interface RequestOptions {`);
  lines.push(`  params?: Record<string, string | number | boolean>;`);
  lines.push(`  query?: Record<string, string | number | boolean>;`);
  lines.push(`  headers?: Record<string, string>;`);
  lines.push(`  body?: unknown;`);
  lines.push(`  formData?: FormData;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`export class ${className} {`);
  lines.push(`  constructor(private baseUrl: string = ${JSON.stringify(api.servers[0] ?? "")}, private defaultHeaders: Record<string, string> = {}) {}`);
  lines.push("");
  for (const endpoint of api.endpoints) {
    lines.push(`  /** ${escapeJsDoc(endpoint.description ?? endpoint.title)} */`);
    lines.push(`  async ${toMethodName(endpoint)}<T = unknown>(options: RequestOptions = {}): Promise<{ status: number; data: T }> {`);
    lines.push(`    return this.request<T>(${JSON.stringify(endpoint.method)}, ${JSON.stringify(endpoint.path)}, options);`);
    lines.push(`  }`);
    lines.push("");
  }
  lines.push(`  private async request<T>(method: string, path: string, options: RequestOptions): Promise<{ status: number; data: T }> {`);
  lines.push(`    let url = this.baseUrl.replace(/\\/$/, "") + path;`);
  lines.push(`    if (options.params) {`);
  lines.push(`      Object.entries(options.params).forEach(([k, v]) => { url = url.replace("{" + k + "}", encodeURIComponent(String(v))); });`);
  lines.push(`    }`);
  lines.push(`    if (options.query) {`);
  lines.push(`      const qs = new URLSearchParams();`);
  lines.push(`      Object.entries(options.query).forEach(([k, v]) => qs.set(k, String(v)));`);
  lines.push(`      url += (url.includes("?") ? "&" : "?") + qs.toString();`);
  lines.push(`    }`);
  lines.push(`    const headers = { ...this.defaultHeaders, ...(options.headers ?? {}) };`);
  lines.push(`    let body: BodyInit | undefined;`);
  lines.push(`    if (options.formData) { body = options.formData; }`);
  lines.push(`    else if (options.body !== undefined) { headers["Content-Type"] = headers["Content-Type"] ?? "application/json"; body = JSON.stringify(options.body); }`);
  lines.push(`    const res = await fetch(url, { method, headers, body });`);
  lines.push(`    const data = await res.json().catch(() => null) as T;`);
  lines.push(`    return { status: res.status, data };`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");
  lines.push(`export default ${className};`);
  return lines.join("\n");
}

function toClassName(title: string): string {
  return title.replace(/[^a-zA-Z0-9]/g, " ").split(/\s+/).filter(Boolean).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

function toMethodName(endpoint: EndpointSpec): string {
  const path = endpoint.path.replace(/[{}]/g, "").replace(/[^a-zA-Z0-9]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
  return `${endpoint.method.toLowerCase()}_${path || "root"}`;
}

function escapeJsDoc(text: string): string {
  return text.replace(/\*\//g, "* /").replace(/\n/g, " ");
}
